return {
	"NStefan002/screenkey.nvim",
	lazy = false,
	opts = {
		version = "*",
	},
	config = function(opts)
		require("screenkey").setup({
			win_opts = {
				row = 0, --vim.o.lines - vim.o.cmdheight - 1,
				col = vim.o.columns - 1,
				relative = "editor",
				anchor = "NE",
				width = 20,
				height = 1,
				border = "rounded",
				title = "",
			},
			compress_after = 2,
			clear_after = 5,
			disable = {
				filetypes = {},
				buftypes = {},
			},
			show_leader = true,
			group_mappings = false,
			display_infront = {},
			display_behind = {},
			keys = {
				["<TAB>"] = "󰌒",
				["<CR>"] = "󰌑",
				["<ESC>"] = "Esc",
				["<SPACE>"] = "␣",
				["<BS>"] = "󰌥",
				["<DEL>"] = "Del",
				["<LEFT>"] = "",
				["<RIGHT>"] = "",
				["<UP>"] = "",
				["<DOWN>"] = "",
				--["<HOME>"] = "Home",
				--["<END>"] = "End",
				--["<PAGEUP>"] = "PgUp",
				--["<PAGEDOWN>"] = "PgDn",
				["<INSERT>"] = "Ins",
				["<F1>"] = "󱊫",
				["<F2>"] = "󱊬",
				["<F3>"] = "󱊭",
				["<F4>"] = "󱊮",
				["<F5>"] = "󱊯",
				["<F6>"] = "󱊰",
				["<F7>"] = "󱊱",
				["<F8>"] = "󱊲",
				["<F9>"] = "󱊳",
				["<F10>"] = "󱊴",
				["<F11>"] = "󱊵",
				["<F12>"] = "󱊶",
				["CTRL"] = "Ctrl",
				["ALT"] = "Alt",
				--["SUPER"] = "󰘳",
				["<leader>"] = "<leader>",
			},
		})
		-- run screenkey off rip
		vim.cmd("Screenkey")
	end,
}
